server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tmall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  application:
    name: service-provider
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
mybatis:
  type-aliases-package: com.example.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    #register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    #fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka

